---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: test
    image: ubuntu:20.04
    commands:
      - echo "Goodbye World"
    when:
      event:
        - push
        - tag
