---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      kubernetes.io/os: linux
  template:
    metadata:
      labels:
        kubernetes.io/os: linux
    spec:
      imagePullSecrets:
        - name: gitlab
      containers:
        - name: nginx
          image: registry.go2cloudten.com/it/docker/proxy
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 22
            - containerPort: 80
            - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  # externalIPs:
  #   - 192.168.185.9
  selector:
    kubernetes.io/os: linux
  ports:
    - name: https
      nodePort: 443
      port: 443
      targetPort: 443
    - name: http
      nodePort: 80
      port: 80
      targetPort: 80
    - name: ssh
      nodePort: 22
      port: 22
      targetPort: 22
